# Generated by Django 6.0.4 on 2026-05-09 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, unique=True)),
                ('value', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('radiologist', 'Radiologist'), ('clinician', 'Clinician'), ('admin', 'Administrator'), ('researcher', 'Researcher')], default='clinician', max_length=20)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image_filename', models.CharField(max_length=255)),
                ('image_size', models.IntegerField()),
                ('predicted_class', models.CharField(choices=[('Adenocarcinoma', 'Adenocarcinoma'), ('Large Cell Carcinoma', 'Large Cell Carcinoma'), ('Normal / Benign', 'Normal / Benign'), ('Squamous Cell Carcinoma', 'Squamous Cell Carcinoma')], max_length=50)),
                ('confidence_score', models.FloatField()),
                ('adenocarcinoma_prob', models.FloatField()),
                ('large_cell_prob', models.FloatField()),
                ('normal_prob', models.FloatField()),
                ('squamous_cell_prob', models.FloatField()),
                ('is_uncertain', models.BooleanField(default=False)),
                ('uncertainty_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('heatmap_base64', models.TextField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_predict_user_id_d7f70f_idx'), models.Index(fields=['patient_id'], name='api_predict_patient_c15d99_idx')],
            },
        ),
    ]
