# Generated by Django 6.0.4 on 2026-05-09 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('', 'Not specified'), ('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('national_id', models.CharField(blank=True, max_length=80, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, default='CT analysis', max_length=255)),
                ('status', models.CharField(default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='predictionrecord',
            name='api_predict_patient_c15d99_idx',
        ),
        migrations.RenameField(
            model_name='predictionrecord',
            old_name='patient_id',
            new_name='legacy_patient_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='api.patient'),
        ),
        migrations.AddField(
            model_name='patientepisode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_episodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientepisode',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='api.patient'),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='api.patientepisode'),
        ),
        migrations.AddIndex(
            model_name='predictionrecord',
            index=models.Index(fields=['legacy_patient_id'], name='api_predict_legacy__2f69d3_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_id'], name='api_patient_patient_c2ad00_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['full_name'], name='api_patient_full_na_5c31ee_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['national_id'], name='api_patient_nationa_c03ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='patientepisode',
            index=models.Index(fields=['patient', '-created_at'], name='api_patient_patient_cbf7c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patientepisode',
            unique_together={('patient', 'episode_number')},
        ),
    ]
